- backends/main.py
- requirements.txt
Endpoint supporting an uploaded document file and pre-processing into an .md file.
> Feature/HBAI-87: Pre-process documents

- package.json
- renderer/pages/index.js
- Removing <Head> component fixes prod crash.
- Update project descr.
> HBAI-107: Fix crash on production builds

- backends/main.py
Create new docs in specific folder.
Check if headers exist.
> HBAI-87: Fix file upload

- .gitignore
- backends/embedding/embedding.py
- backends/main.py
- requirements.txt
This adds a main endpoint that uses several functions to first process an uploaded document then chunk it and embed it into a ChromaDB database and save to disk.
It also adds functions for hallucination and truthiness verification.
> Feature/HBAI-106: Add document embedding

- main/utils/downloader.js
- package.json
- renderer/components/text-model-browser/ModelCard.tsx
- requirements.txt
- yarn.lock
Adds error handling when a folder is write-protected and requests timeout.
> Bugfix/HBAI-118: Upgrades to modules and Next.js + error handling

- main/electron.js
- main/utils/downloader.js
- package.json
- renderer/components/text-inference-config/TextInferenceConfigMenu.tsx
- renderer/components/text-model-browser/ModelBrowser.tsx
- renderer/components/text-model-browser/ModelCard.tsx
- renderer/components/text-model-browser/useDownloader.ts
- renderer/models/models.ts
- renderer/pages/home.tsx
- renderer/utils/localStorage.ts
Add more error handling to downloader...
> HBAI-118-2

- .gitignore
- backends/embedding/embedding.py
- backends/inference/text_llm.py
- backends/main.py
- renderer/components/text-model-browser/ModelBrowser.tsx
- renderer/pages/home.tsx
Refactor of #8 HBAI-106
This PR refactors the chromadb and LlamaIndex logic for embeddings and Q&A on documents.
It modularizes the logic.
> Enhancement/HBAI-114 Load Embeddings from fresh app start

- backends/embedding/embedding.py
- backends/main.py
- Added several CRUD endpoints for manipulating memories and collections of memories.
- Modularized some code into the embeddings file.
- Added some basic document level functionality (open file in explorer).
- Download files from url and embed as memory.
- Add LlamaIndex support
- Change how parsed files are named
> Feature/HBAI-115: Add endpoints for memories (CRUD)

- README.md
- backends/embedding/embedding.py
- backends/inference/text_llama_index.py
- backends/inference/text_routes.py
- backends/main.py
- backends/routes/__init__.py
- backends/routes/api.py
- backends/server/classes.py
- backends/server/common.py
- renderer/components/text-inference-config/TextInferenceConfigMenu.tsx
- renderer/models/models.ts
- renderer/pages/home.tsx
- requirements.txt
This deprecates the llama-cpp-python[server] module and uses llama-index's query() and completions() calls.
> Feature/HBAI-77: Support high level inference api

- backends/server/common.py
Fix some issues with dupes and commas.
> Bugfix/HBAI-135: Fix user input "tags"

- README.md
- backends/embedding/embedding.py
- backends/inference/text_llama_index.py
- backends/main.py
- backends/server/classes.py
- backends/server/common.py
- Edited readme.
- Minor fixes to prompt args logic.
- Refactor augmented retrieval logic.
- Add prompt converter funcs to format message/completion.
> HBAI-169: Implement Prompt Formats for each LLM

- .vscode/settings.json
- backends/embedding/embedding.py
- backends/main.py
- backends/routes/api.py
- backends/server/classes.py
- backends/server/common.py
- Refactor endpoints to save settings data to disk for each app mode
> Feature/HBAI-188: Support playground mode menus

- backends/main.py
- backends/routes/api.py
- backends/server/classes.py
- Create endpoint to eject model
- Added model name to `model` settings
- Always unload model if one is already loaded
> Feature/HBAI-171: Support unloading model

- backends/server/classes.py
Pydantic was blocking b/c `metadata` not passed.
> HBAI-201 Fix undefined props for `updateDocument`

- .env.example
- README.md
- backends/main.py
- package.json
Add env keys for ssl file names.
> HBAI-273: Run http or https depending on env vars.

- .env.example
- README.md
- backends/main.py
- inno-setup-config.iss
- package.json
- py-to-exe-config.dev.json
- py-to-exe-config.prod.json
- Bundle .env.example with the app.
- Start SSL server only if the .env var "SSL" is set to "true".
- Edit readme.
> HBAI-278: Handle http/https

- backends/core/classes.py
- backends/inference/classes.py
- backends/inference/route.py
- backends/main.py
- package.json
Check the "retrievalType" of attention setting when choosing inference flow
> HBAI-285: Check "retrievalType" attention setting

- README.md
- assets/api-docs.md
- assets/build-steps.md
- assets/bundling-packaging.md
- assets/deploy-release.md
- assets/development.md
- assets/getting-started.md
- assets/how-to-use.md
> HBAI-299: Cleanup readme

- assets/deploy-release.md
- assets/development.md
- backends/api_server.py
- backends/core/common.py
- backends/main.py
- backends/ui/api_ui.py
- backends/ui/public/global.js
- backends/ui/public/main.js
- backends/ui/public/settings.html
- backends/ui/view.py
- py-to-exe-config.dev.json
- py-to-exe-config.prod.json
- requirements.txt
- start server with https when ssl enabled
- “WebUI” input used to determine which webui to point to when generating QR code
> Bugfix/HBAI-303: Enable SSL server via startup page

- backends/api_server.py
- backends/core/classes.py
- backends/core/common.py
- backends/embeddings/file_loaders.py
- backends/main.py
- backends/services/route.py
- backends/ui/public/global.css
- backends/ui/public/loading.js
- backends/ui/public/main.css
- backends/ui/public/main.html
- backends/ui/public/main.js
- backends/ui/view.py
- package.json
- When creating api server, check if one exists on specified port first before creating
- Create a banner message on splash page
- Add link to download updates
> Feature/HBAI-322 Dont create dupe server

- backends/api_server.py
- backends/core/classes.py
- backends/core/common.py
- backends/inference/agent.py
- backends/inference/classes.py
- backends/inference/helpers.py
- backends/inference/llama_cpp.py
- backends/inference/route.py
- backends/services/route.py
- backends/storage/route.py
- backends/tools/built-in/retrieval.py
- backends/tools/helpers.py
- backends/tools/tool.py
- backends/updater.py
- package.json
- public/prompt_formats.json
- public/text_model_configs.json
- Support native func calling
- Fixes for stop/pause text inference
- Set llama.cpp version in package.json
- Added /stop endpoint for pausing inference
> Feature/HBAI-339: Support native func calling

- backends/core/classes.py
- backends/inference/agent.py
- backends/inference/classes.py
- backends/inference/grammars/json.gbnf
- backends/inference/grammars/json_arr.gbnf
- backends/inference/llama_cpp.py
- backends/inference/route.py
- backends/tools/classes.py
- backends/tools/helpers.py
- backends/tools/tool.py
- package.json
- public/prompt_formats.json
- public/text_model_configs.json
Add an extra layer of determinism by constraining the output tokens by a json schema. This should ensure the response only contains json.
> Feature/HBAI-344: Support JSON constrained output

- backends/ui/api_ui.py
- backends/ui/public/loading.js
- backends/ui/public/main.css
- backends/ui/public/main.html
- backends/ui/public/main.js
- backends/updater.py
- package.json
> features/HBAI-260: Add app version to splash page

- assets/how-to-use.md
- backends/inference/llama_cpp.py
- Prevent terminal popup when llama-cli runs.
- Update docs.
> bugfix/HBAI-260: Stop terminal pop-up

- backends/api_server.py
- backends/embeddings/vector_storage.py
- backends/inference/llama_cpp.py
- backends/tools/built_in_functions/retrieval.py
If multiple collections are assigned, run RAG on each one and accumulate/return the results.
> Feature/HBAI-371: Support multiple assigned memory collections
